### ISSUE TITLE
Replace Announcing Soon under speakers to "Become a speaker - propose a session"

### ISSUE THREAD

**Issue by SathyaBhat** [awsug/communityday.awsug.in#1]
For the duration the CFPs are open, we should mention "Become a speaker - propose a session" with a link to the the [CFP Page](https://sessionize.com/awscommunitydayindia/)

**Comment by gaurav-kamboj** [comment]
Done. Updated the page with "Become a speaker - propose a session" and hyperlink to CFP site.
