### ISSUE TITLE
Update site to announce CFP open for AWS Community Day South Asia 2021

### ISSUE THREAD

**Issue by SathyaBhat** [awsug/communityday.awsug.in#31]
We need to update the site to announce CFPs are open for AWS Community Day South Asia . The call to action is a button which links to https://sessionize.com/aws-community-day/

Till we have new design, we can re-use the existing components and design. You can see how the 2020 CFP looked like by checking out commit a3dd17f60f8078d04a79fb7a17d02bdce792fed2

**Comment by fz9** [comment]
Till the new repo is created/cloned here, I have completed this under: https://github.com/fz9/communityday.awsug.asia

**Comment by plug-n-play** [comment]
Thanks @fz9 

Moved it to https://github.com/awsug/communityday.awsug.asia
